spring:
  datasource:
    url: "jdbc:mysql://192.168.100.34:3306/IOT"
    username: usr1
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: validation
server:
  port: 80
mqtt:
  username: H7WXTcZedIlpopjLhLhJ
  password: ''
  host-url: tcp://demo.thingsboard.io:1883      # The address and port of your own server need to be changed
  clientID: mqtt-client-2317					# This change is not optional, but different clients must not be the same
  default-topic: v1/devices/me/telemetry	    # Default theme
  timeout: 100
  keepalive: 100
sensors:
  motion: 'lEtZ0LvBAkGaYIXz2PCK'
  voltage: 'reXKyNioBkbKhB57xZTc'